#!/usr/bin/env bash
# Run the three AutoDock Vina docking jobs described in Supplement Section 2.5
# (positive control, test protein, negative control), all against kinetin.
#
# Requires: AutoDock Vina 1.2.x on PATH, and receptor/ligand PDBQT files
# already generated by 01_prepare_ligand.sh and 02_prepare_receptor.sh.
set -euo pipefail

mkdir -p ../results/vina_logs

CONFIGS=(
  "vina_configs/3T4S_AHK4_positive_control.conf"
  "vina_configs/6HGP_APRT_test.conf"
  "vina_configs/DinB_negative_control.conf"
)

for cfg in "${CONFIGS[@]}"; do
  echo "=== Running: ${cfg} ==="
  vina --config "${cfg}"
done

echo "All docking runs complete. See ../results/vina_logs/*.log for binding energies."
echo "Compare against ../results/docking_summary.csv (values reported in the manuscript)."
